### ISSUE TITLE
Attempting to encrypt into image or video throws NotImplementedError

### ISSUE THREAD

**Issue by joeyio** [Kunal-Attri/Data-Security-using-Cryptography-and-Steganography#1]
The process fails partway through and throws the following error:

 

> Traceback (most recent call last):
> 
>   File "/home/joeyio/ssl/Data-Security-using-Cryptography-and-Steganography/main.py", line 63, in <module>
>     main()
> 
>   File "/home/joeyio/ssl/Data-Security-using-Cryptography-and-Steganography/main.py", line 28, in main
>     secure.secure_file(fName)
> 
>   File "/home/joeyio/anaconda3/envs/vidSteg/lib/python3.9/site-packages/multipledispatch/dispatcher.py", line 439, in __call__
>     return func(self.obj, *args, **kwargs)
> 
>   File "/home/joeyio/ssl/Data-Security-using-Cryptography-and-Steganography/lib/Secure.py", line 17, in secure_file
>     self.stego.stego(f)
> 
>   File "/home/joeyio/anaconda3/envs/vidSteg/lib/python3.9/site-packages/multipledispatch/dispatcher.py", line 435, in __call__
>     raise NotImplementedError(
> 
> NotImplementedError: Could not find signature for stego: <NoneType>

I'm running an Anaconda environment in WSL on Windows 11 64 bit. All the dependencies seem to be in place.

**Comment by Kunal-Attri** [comment]
Thanks for the issue.  Can you confirm, did you change anything in Stego.py? Specifically at line 17-18.
Code at line 17-18 should be:
> @dispatch(str)
> def stego(self, file_path):

In the error, it looks like, dispatcher is trying to find a overloaded version of stego mathod with a specific signature, but it is not able to find that.

Also, check type of argument passed to self.stego.stego at line 17 in Secure.py.

**Comment by Kunal-Attri** [comment]
It's been a long time since you updated last time. I am closing this issue, assuming it's fixed in recent updates pushed to repo.
